# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: build
    silent: true

  iex:
    deps:
      - build
    cmds:
      - iex -S mix

  build:
    deps:
      - build_c
      - build_odin
      - build_zig
    aliases: [b]

  build_odin:
    cmds:
      - mkdir -p ./nif/obj/odin
      - odin build nifs -reloc-mode=pic -build-mode:shared -out:nif/obj/odin/nifs.so
    generates:
      - ./nif/obj/odin/nifs.so
    sources:
      - ./nifs/*
    silent: true

  build_c:
    cmds:
      - mkdir -p ./nif/obj/c
      - gcc -fpic -shared -I $ERL_HEADERS -o nif/obj/c/nifs.so nif/c/*.c
    generates:
      - ./nif/obj/c/nifs.so
    sources:
      - ./nif/c/*.c
    silent: true

  build_zig:
    cmds:
      - mkdir -p ./nif/obj/zig
      - zig build-lib --library c -dynamic -fPIC  -I $ERL_HEADERS -femit-bin=nif/obj/zig/nifs.so nif/zig/nifs.zig
    generates:
      - nif/obj/zig/nifs.so
    sources:
      - ./nif/zig/*.zig
    silent: true

  tests:
    deps: [main_tests]
    aliases: [t]
  main_tests:
    cmds:
      - odin run erldin_tests
    silent: true
    sources:
      - ./erldin/*
      - ./erldin_tests/*
    aliases: [et]
  clean:
    cmds:
      - rm -rf ./nif/obj
    silent: true

interval: 250ms
