# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: build
    silent: true
  iex:
    deps:
      - build
    cmds:
      - iex -S mix
  build:
    deps:
      - build_c
      - build_odin
      - build_zig
    aliases: [b]
  build_odin:
    cmds:
      - mkdir -p ./nif/obj/odin
      - odin build hello_from_odin -reloc-mode=pic -build-mode:shared
      - mv hello_from_odin.so ./nif/obj/odin/hello_from_odin.so
    generates:
      - ./hello_from_odin.so
    sources:
      - ./hello_from_odin/*
    silent: true
  build_c:
    cmds:
      - mkdir -p ./nif/obj/c
      - gcc -fpic -shared -I $ERL_HEADERS -o nif/obj/c/hello_world.so nif/c/hello_world.c
    generates:
      - ./nif/obj/c/hello_world.so
    sources:
      - ./nif/c/hello_world.c
    silent: true
  build_zig:
    cmds:
      - mkdir -p ./nif/obj/zig
      - zig build-lib --library c -dynamic -fPIC  -I $ERL_HEADERS -femit-bin=nif/obj/zig/libzig_hello_world.so nif/zig/hello_world.zig
    generates:
      - ./nif/obj/zig/hello_world.so
    sources:
      - ./nif/zig/*.zig
    silent: true
  tests:
    deps: [main_tests]
    aliases: [t]
  main_tests:
    cmds:
      - odin run erldin_tests
    silent: true
    sources:
      - ./erldin/*
      - ./erldin_tests/*
    aliases: [et]
  clean:
    cmds:
      - rm -rf ./nif/obj
    silent: true

interval: 250ms
