# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task: build
    silent: true

  iex:
    deps:
      - build
    cmds:
      - iex -S mix

  build:
    deps:
      - build_c
      - build_odin
      - build_zig
    aliases: 
      - b

  build_odin:
    cmds:
      - mkdir -p ./nif/obj/odin
      - odin build nifs -reloc-mode=pic -build-mode:shared -out:nif/obj/odin/nifs.so
    generates:
      - ./nif/obj/odin/nifs.so
    sources:
      - ./nifs/*.odin
      - ./erldin/*.odin
    silent: true

  build_c:
    cmds:
      - mkdir -p ./nif/obj/c
      - gcc -fpic -shared -I $ERL_HEADERS -o nif/obj/c/nifs.so nif/c/nifs.c
      - gcc -fpic -shared -I $ERL_HEADERS -o nif/obj/c/slots.so nif/c/slots.c
    generates:
      - ./nif/obj/c/nifs.so
      - ./nif/obj/c/slots.so
    sources:
      - ./nif/c/*.c
    silent: true

  build_zig:
    cmds:
      - mkdir -p ./nif/obj/zig
      - zig build-lib --library c -dynamic -fPIC  -I $ERL_HEADERS -femit-bin=nif/obj/zig/nifs.so nif/zig/nifs.zig
      - zig build-lib --library c -dynamic -fPIC  -I $ERL_HEADERS -femit-bin=nif/obj/zig/slots.so nif/zig/slots.zig
    generates:
      - nif/obj/zig/nifs.so
      - nif/obj/zig/slots.so
    sources:
      - ./nif/zig/*.zig
    silent: true

  tests:
    deps:
      - elixir_tests
    aliases: 
      - t
  elixir_tests:
    deps:
      - build
    cmds:
      - mix test
    sources:
      - ./test/*
    silent: true
    aliases:
      - et
  clean:
    cmds:
      - rm -rf ./nif/obj
    silent: true

interval: 250ms
